-- Ajouter les stations radio existantes
INSERT INTO radio_stations (name, genre, country, frequency, stream_url, logo_url, description, website, is_active) VALUES
('NRJ', 'Pop', 'France', '100.3 FM', 'https://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/NRJ_2015_logo.png', 'Hit Music Only', 'https://www.nrj.fr', true),
('RTL', 'Talk/News', 'France', '104.3 FM', 'https://streaming.radio.rtl.fr/rtl-1-44-128', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/RTL_logo_2015.svg', 'La première radio de France', 'https://www.rtl.fr', true),
('France Inter', 'Talk/News', 'France', '87.8 FM', 'https://direct.franceinter.fr/live/franceinter-midfi.mp3', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/France_Inter_logo_2021.svg', 'Radio du service public français', 'https://www.franceinter.fr', true),
('Europe 1', 'Talk/News', 'France', '104.7 FM', 'https://europe1.lmn.fm/europe1.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Europe_1_logo_2008.svg/1200px-Europe_1_logo_2008.svg.png', 'La radio de tous les débats', 'https://www.europe1.fr', true),
('RMC', 'Talk/News', 'France', '103.1 FM', 'https://rmc.bfmtv.com/rmcinfo-mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/RMC_logo_2017.svg/1200px-RMC_logo_2017.svg.png', 'Radio Monte Carlo', 'https://rmc.bfmtv.com', true),
('Fun Radio', 'Pop', 'France', '101.9 FM', 'https://streaming.radio.funradio.fr/fun-1-44-128', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Fun_Radio_logo_2013.svg/1200px-Fun_Radio_logo_2013.svg.png', 'Fun Radio - Son Dancefloor', 'https://www.funradio.fr', true),
('Skyrock', 'Rap/Hip-Hop', 'France', '96.0 FM', 'https://icecast.skyrock.net/s/natio_mp3_128k', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Skyrock_logo_2019.svg/1200px-Skyrock_logo_2019.svg.png', 'Première radio jeune', 'https://skyrock.fm', true),
('Nostalgie', 'Variété', 'France', '90.4 FM', 'https://scdn.nrjaudio.fm/audio1/fr/30601/mp3_128.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Nostalgie_logo_2008.svg/1200px-Nostalgie_logo_2008.svg.png', 'Les plus belles chansons', 'https://www.nostalgie.fr', true),
('Chérie FM', 'Pop', 'France', '91.3 FM', 'https://scdn.nrjaudio.fm/audio1/fr/30201/mp3_128.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Ch%C3%A9rie_FM_logo_2008.svg/1200px-Ch%C3%A9rie_FM_logo_2008.svg.png', 'Chérie FM - La plus belle musique', 'https://www.cheriefm.fr', true),
('Virgin Radio', 'Rock', 'France', '103.5 FM', 'https://virginradio.lmn.fm/virginradiofrance.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Virgin_Radio_logo_2008.svg/1200px-Virgin_Radio_logo_2008.svg.png', 'Virgin Radio - Rock Alternative', 'https://www.virginradio.fr', true),
('Jazz Radio', 'Jazz', 'France', '97.8 FM', 'https://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Jazz_Radio_logo_2017.svg/1200px-Jazz_Radio_logo_2017.svg.png', 'Jazz Radio - All Jazz', 'https://www.jazzradio.fr', true),
('FIP', 'Électronique', 'France', '105.1 FM', 'https://direct.fipradio.fr/live/fip-midfi.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/FIP_logo_2005.svg/1200px-FIP_logo_2005.svg.png', 'FIP - Tout nouveau, tout FIP', 'https://www.fip.fr', true),
('Radio Classique', 'Classique', 'France', '101.1 FM', 'https://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Radio_Classique_logo_2017.svg/1200px-Radio_Classique_logo_2017.svg.png', 'Radio Classique - La plus belle musique', 'https://www.radioclassique.fr', true),
('RFM', 'Pop', 'France', '103.9 FM', 'https://rfm-live-mp3-128.scdn.arkena.com/rfm.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/RFM_logo_2008.svg/1200px-RFM_logo_2008.svg.png', 'RFM - Party Fun', 'https://www.rfm.fr', true),
('Rire & Chansons', 'Variété', 'France', '97.4 FM', 'https://scdn.nrjaudio.fm/audio1/fr/30401/mp3_128.mp3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Rire_%26_Chansons_logo_2008.svg/1200px-Rire_%26_Chansons_logo_2008.svg.png', 'Rire & Chansons - 100% Humour', 'https://www.rireetchansons.fr', true);
